-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS reto.tr_empleados
(
    emp_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    emp_cedula text COLLATE pg_catalog."default" NOT NULL,
    emp_apellido text COLLATE pg_catalog."default" NOT NULL,
    emp_correo text COLLATE pg_catalog."default" NOT NULL,
    emp_fecha timestamp without time zone NOT NULL,
    emp_telefono text COLLATE pg_catalog."default" NOT NULL,
    emp_direccion text COLLATE pg_catalog."default" NOT NULL,
    emp_estado text COLLATE pg_catalog."default" NOT NULL,
    emp_nombre text COLLATE pg_catalog."default" NOT NULL,
    emp_usu_id integer NOT NULL,
    CONSTRAINT usu_empleados_pkey PRIMARY KEY (emp_id)
);

CREATE TABLE IF NOT EXISTS reto.tr_rol
(
    rol_id numeric NOT NULL,
    rol_nombre text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tr_rol_pkey PRIMARY KEY (rol_id)
);

CREATE TABLE IF NOT EXISTS reto.tr_usuarios
(
    usu_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    usu_usuario text COLLATE pg_catalog."default" NOT NULL,
    usu_clave text COLLATE pg_catalog."default" NOT NULL,
    usu_rol_id integer,
    CONSTRAINT tr_usuarios_pkey PRIMARY KEY (usu_id)
);

CREATE TABLE IF NOT EXISTS reto.tr_vacuna
(
    vac_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vac_dosis numeric NOT NULL,
    vac_tipo text COLLATE pg_catalog."default" NOT NULL,
    vac_fecha timestamp without time zone NOT NULL,
    vac_emp_id integer NOT NULL,
    CONSTRAINT tb_vacuna_pkey PRIMARY KEY (vac_id)
);

ALTER TABLE IF EXISTS reto.tr_empleados
    ADD CONSTRAINT fk_usuarios FOREIGN KEY (emp_usu_id)
    REFERENCES reto.tr_usuarios (usu_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS reto.tr_usuarios
    ADD CONSTRAINT fk_rol FOREIGN KEY (usu_rol_id)
    REFERENCES reto.tr_rol (rol_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS reto.tr_vacuna
    ADD CONSTRAINT fk_empleados FOREIGN KEY (vac_emp_id)
    REFERENCES reto.tr_empleados (emp_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;